### ISSUE TITLE
[Suggestion] NetherFoundation addons

### ISSUE THREAD

**Issue by Skillotic0703** [TehSeph/NetherFoundation#5]
I think you should create addons for your mod. There would be one addon per mod.
I think the easiest addon to make would be the AE2 addon. There are only 2 ores (certus quartz and charged certus quartz).

**Comment by TehSeph** [comment]
The mod itself is already an addon for [Thermal Foundation](https://minecraft.curseforge.com/projects/thermal-foundation). It wouldn't make much sense to make addon mods for an addon mod.

The original idea was to add a bunch of nether-related items and monsters, similar to how TF adds some basic mod items and monsters to the overworld. I decided to release it instead as a nether ores mod when I failed to think of any clever ideas but still wanted a lightweight solution to nether ores.

If you're looking for something with more mod compatibility and more ores, I suggest looking at [Netherending Ores](https://minecraft.curseforge.com/projects/netherending-ores). It looks fantastic. 😺
